[env]
platform = ch32v
framework = noneos-sdk
board = genericCH32X035G8U6
;turn off the compilation of the built-in debug implementation
board_build.use_builtin_debug_code = no
upload_protocol = isp

[env:debug]

[env:release]
